name: Build and deploy Doxygen documentation

on:
  push:
    branches: main
  
jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2



    # Build Doxygen documentation
    # mattnotmitt/doxygen-action
    # https://github.com/marketplace/actions/doxygen-action

    - name: Build Doxygen
      uses: mattnotmitt/doxygen-action@v1.9.5
      with:
        working-directory: '.'
        doxyfile-path: './Doxyfile'
        enable-latex: true


    # Deploy Doxygen documentation
    # peaceiris/actions-gh-pages
    # https://github.com/peaceiris/actions-gh-pages

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
